name: Test
on: [push]
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Test
      shell: pwsh
      run: docker run -v "$($PWD):/PowerShellBuild" mcr.microsoft.com/powershell:lts-7.2-ubuntu-jammy ./build.ps1 -Task Test -Bootstrap  # ./build.ps1 -Task Test -Bootstrap
    - name: Test Windows PowerShell
      if: runner.os == 'Windows'
      shell: powershell
      run: ./build.ps1 -Task Test -Bootstrap
